//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListStudents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentList
    {
        public int StudentId { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Grade { get; set; }
    }
}
